### ISSUE TITLE
Arduino local installation failed

### ISSUE THREAD

**Issue by boyankuo** [IoTtalk/iottalk-py#23]
requirements.txt
```
paho-mqtt==1.5.0
requests~=2.22.0
```
執行 pip install . 時會壞掉如下圖
```
 ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-VHeiBp/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-VHeiBp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-VHeiBp/pip-egg-info
         cwd: /tmp/pip-req-build-VHeiBp/
    Complete output (1 lines):
    error in iottalk-py setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. 
```
要將 requirements.txt 改成下圖才可執行
```
paho-mqtt
requests
```

**Comment by iblislin** [comment]
大概是舊的 ~distutils~ setuptools 的問題。

**Comment by iblislin** [comment]
```
python version : 2.7.3
distribute version : 0.6.21 (setuptools)
```

**Comment by iblislin** [comment]
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/operations/prepare.py", line 243, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/req/req_install.py", line 307, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/index.py", line 484, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/index.py", line 442, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/index.py", line 587, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/index.py", line 705, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/index.py", line 814, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_internal/download.py", line 397, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/cachecontrol/adapter.py", line 42, in send
    cached_response = self.controller.cached_request(request)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/cachecontrol/controller.py", line 137, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/cachecontrol/serialize.py", line 98, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/cachecontrol/serialize.py", line 190, in _loads_v4
    cached = msgpack.loads(data, encoding='utf-8')
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/msgpack/fallback.py", line 121, in unpackb
    ret = unpacker._unpack()
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/msgpack/fallback.py", line 600, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/msgpack/fallback.py", line 600, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/msgpack/fallback.py", line 560, in _unpack
    typ, n, obj = self._read_header(execute)
  File "/usr/lib/python2.7/site-packages/pip-10.0.0-py2.7.egg/pip/_vendor/msgpack/fallback.py", line 442, in _read_header
    obj = struct.unpack_from(">H", self._buffer, self._buff_i)[0]
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray
```

**Comment by iblislin** [comment]
在 Arduino Yun Rev1 中 python 2.7.3 以下要搭配 pip 10.0.1
